# ===== Language servers settings =====
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
trusted = 1
hook_add = '''
" Use K to show documentation in preview window
nmap <silent> gd :call <SID>show_documentation()<CR>
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
'''