# Syntax heighlight
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'akhaku/vim-java-unused-imports'

[[plugins]]
repo = 'tasn/vim-tsx'

[[plugins]]
repo = 'ternjs/tern_for_vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'hashivim/vim-terraform'
# Tools
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
augroup NERD
    au!
    autocmd VimEnter * NERDTree
    autocmd VimEnter * wincmd p
augroup END
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Theme
[[plugins]]
repo = 'tomasiser/vim-code-dark'

# js/ts
[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

# kill buffer
[[plugins]]
repo = 'qpkorr/vim-bufkill'